-- VIEW MATERIALIZED
CREATE MATERIALIZED VIEW LISTA_CLIENTE_ESTILOS_CERVEJAS AS
	SELECT
	DISTINCT E.NOME  NOME_ESTILO_CERVEJA, A.NOME NOME_CLIENTE
	FROM CLIENTE A, VENDA B, ITEM_VENDA C, CERVEJA D, ESTILO E
	WHERE
	A.CODIGO = B.CODIGO_CLIENTE 	AND
	B.CODIGO = C.CODIGO_VENDA		AND
	D.CODIGO = C.CODIGO_CERVEJA		AND
	E.CODIGO = D.CODIGO_ESTILO
	ORDER BY A.NOME ASC
WITH NO DATA;

-- ATUALIZANDO VIEW MATERIALIZED
REFRESH MATERIALIZED VIEW LISTA_CLIENTE_ESTILOS_CERVEJAS;

-- CCONSULTANDO VIEW MATERIALIZED
SELECT * FROM LISTA_CLIENTE_ESTILOS_CERVEJAS;