-- SCRIPT PARA AS QUESTÕES 6 - 7 - 8

-- QUESTÃO 6 CREATE USER
CREATE USER USR_RELATORIO WITH PASSWORD '12345678';

-- QUESTÃO 7 REVOGAR TODA E QUALQUER PERMISSÃO DE USR_RELATORIO
REVOKE ALL ON DATABASE postgres FROM USR_RELATORIO;

-- QUESTÃO 8 CONCEDER PERMISSÃO A VIEW MATERIALIZED
GRANT SELECT ON VENDA_AUDITORIA TO USR_RELATORIO;
