-- CONSULTAR QUESTÕES 9 - 10 - 11

-- CONSULTA 9 (LISTA DE CERVEJAS VENDIDAS, INCLUSIVE AS QUE NÃO VENDERAM = 0)
-- FOI INCLUÍDO UM INSERT DE CADASTRO PARA 2 CERVEJAS QUE NÃO TERÃO NENHUM REGISTRO DE VENDA
INSERT INTO CERVEJA (CODIGO, SKU, NOME, DESCRICAO, VALOR, TEOR_ALCOOLICO, COMISSAO, SABOR, ORIGEM, CODIGO_ESTILO, QUANTIDADE_ESTOQUE, FOTO, CONTENT_TYPE)
VALUES (5, 'SKU_05', 'CERVEJA_05', 'DES_5', 5, 5, 5, 'SABOR_05', 'ORIGEM_05', 4, 50, 'FOTO_05', 'CONTEXTO_05');

INSERT INTO CERVEJA (CODIGO, SKU, NOME, DESCRICAO, VALOR, TEOR_ALCOOLICO, COMISSAO, SABOR, ORIGEM, CODIGO_ESTILO, QUANTIDADE_ESTOQUE, FOTO, CONTENT_TYPE)
VALUES (6, 'SKU_06', 'CERVEJA_06', 'DES_6', 6, 6, 6, 'SABOR_06', 'ORIGEM_06', 4, 60, 'FOTO_06', 'CONTEXTO_06');

SELECT * FROM CERVEJA;
-- CONSULTA 9
SELECT
A.NOME NOME_CERVEJA, SUM(COALESCE(B.QUANTIDADE, 0)) QTD_VENDIDA
FROM CERVEJA A
FULL OUTER JOIN ITEM_VENDA B ON (A.CODIGO = B.CODIGO_CERVEJA)
GROUP BY A.NOME
ORDER BY A.NOME ASC;

------------------------------------------------
-- CONSULTA 10 LISTA DE VENDAS REALIZADAS POR USUÁRIOS / MÊS
SELECT
B.NOME NOME_USUARIO, EXTRACT(YEAR FROM A.DATA_CRIACAO) ANO_VENDA,
EXTRACT(MONTH FROM A.DATA_CRIACAO) MES_VENDA, SUM(C.QUANTIDADE) QTD_VENDIDA
FROM VENDA A
FULL OUTER JOIN USUARIO B ON (A.CODIGO_USUARIO = B.CODIGO)
FULL OUTER JOIN ITEM_VENDA C ON (C.CODIGO_VENDA = A.CODIGO)
GROUP BY B.NOME, A.DATA_CRIACAO
ORDER BY B.NOME ASC;

-----------------------------------------------------
-- CONSULTA 11 TOTAL COMISSÃO POR USUÁRIO 1
SELECT
B.NOME NOME_USUARIO, SUM(C.QUANTIDADE * D.COMISSAO) TOTAL_COMISSAO
FROM VENDA A
FULL OUTER JOIN USUARIO B ON (A.CODIGO_USUARIO = B.CODIGO)
FULL OUTER JOIN ITEM_VENDA C ON (C.CODIGO_VENDA = A.CODIGO)
FULL OUTER JOIN CERVEJA D ON (D.CODIGO = C.CODIGO_CERVEJA)
WHERE
B.CODIGO = 1
GROUP BY B.NOME
ORDER BY B.NOME ASC;
